# This workflow generates an SLSA provenance file for your project.
# It satisfies level 3 for provenance requirements (https://slsa.dev/spec/v0.1/requirements).
# Developed by OpenSSF (openssf.org), more at https://github.com/slsa-framework/slsa-github-generator.
# The provenance file can be verified using https://github.com/slsa-framework/slsa-verifier.

name: SLSA Generic Generator

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      digests: ${{ steps.hash.outputs.hashes }}

    steps:
      - uses: actions/checkout@v4

      # ========================================================
      # Step 1: Build your artifacts.
      # ========================================================
      - name: Build artifacts
        run: |
          echo "artifact1" > artifact1
          echo "artifact2" > artifact2

      # ========================================================
      # Step 2: Generate provenance subjects (hashes).
      # ========================================================
      - name: Generate subject for provenance
        id: hash
        run: |
          set -euo pipefail
          
          # List the artifacts
          files=$(ls artifact*)
          
          # Compute hashes and store them in a variable
          hashes=$(sha256sum $files | base64 -w0)
          
          # Export the hashes as an output
          echo "hashes=${hashes}" >> "$GITHUB_ENV"
          echo "hashes=${hashes}" >> "$GITHUB_OUTPUT"

  provenance:
    needs: build
    permissions:
      actions: read   # To read the workflow path.
      id-token: write # To sign the provenance.
      contents: write # To add assets to a release.
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.4.0
    with:
      base64-subjects: "${{ needs.build.outputs.digests }}"
      upload-assets: true # Optional: Upload to a new release
